services:
  tubify-user-manager:
    container_name: tubify-user-manager
    image: tubify-user-manager
    expose:
      - "5000"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - JWT_EXPIRES_HOURS=${JWT_EXPIRES_HOURS}
      - JWT_REFRESH_TOKEN_EXPIRES_DAYS=${JWT_REFRESH_TOKEN_EXPIRES_DAYS}
    networks:
      - tubify-net

networks:
  tubify-net:
    external: true